apiVersion: v1
kind: Service
metadata:
  name: cadastro-api-service
  labels:
    app: cadastro-api
spec:
  selector:
    app: cadastro-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer