version: "3.8"

services:
  api:
    image: nginx:latest
    container_name: cadastro-api
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - cadastro-net

  db:
    image: postgres:15
    container_name: cadastro-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - cadastro-net
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cadastro-rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"  # Interface de gerenciamento
    networks:
      - cadastro-net

networks:
  cadastro-net:
    driver: bridge

volumes:
  db-data:
    driver: local